#application configuration
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mariadb://localhost:3306/s3_upload
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
#  profiles:
#    active: development
#  mvc:
#    static-path-pattern: /public/**
#    server:
#      port: 8080

cloud:
  aws:
    region:
      static: eu-north-1
    stack:
      auto: false
application:
  bucket: s3-upload-test-fritz